version: "3.8"

services:
  app:
    container_name: mini-twit-itu-web-api
    image: mini-twit-itu-web-api
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000

